name: Tests

# Define when to run
on:
  schedule:
    - cron:  '30 4 1 * *'
  push:
    branches: ['*']

  pull_request:
    branches: ['*']

  workflow_dispatch:

# Env variables
env:
  CACHE_NUMBER: 0  # increase to reset cache manually

permissions:
  pull-requests: write


# Jobs
jobs:
  bump_version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Needed for tags and full history

      - name: Set up Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Generate new branch name
        id: vars
        run: |
          BRANCH_NAME="version-bump-$(date +'%Y%m%d%H%M%S')"
          echo "branch_name=$BRANCH_NAME" >> $GITHUB_OUTPUT

      - name: Create new branch
        run: |
          git checkout -b ${{ steps.vars.outputs.branch_name }}

      - name: Install bumpversion
        run: |
          python -m pip install --upgrade pip
          pip install bumpversion

      # Step to fetch the PR body and determine version bump type
      - name: Get PR body and determine bump type
        id: pr_info
        run: |
          PR_BODY=$(curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            "https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}" | jq -r '.body')
          
          echo "PR Body: $PR_BODY"
          
          # Determine bump type based on PR body
          if [[ "$PR_BODY" =~ "#major" ]]; then
            echo "bump_type=major" >> $GITHUB_ENV
          elif [[ "$PR_BODY" =~ "#minor" ]]; then
            echo "bump_type=minor" >> $GITHUB_ENV
          else
            echo "bump_type=patch" >> $GITHUB_ENV
          fi

        # For debugging
      - name: Dry run bumpversion with appropriate type
        run: |
          bumpversion ${{ env.bump_type }} --dry-run  # --dry-run shows what would change
          git diff  # Check what files are being modified

      # Run bumpversion with the determined type
      - name: Run bumpversion with appropriate type
        run: |
          bumpversion ${{ env.bump_type }}  # Will be 'patch', 'minor', or 'major'
          git diff

      - name: Check for changes after bump
        run: |
          git log --oneline -n 2
          git show HEAD
          git branch
          git status
          git diff --name-only  # Check which files have changed
          git log -n 1  # Check the last commit, to see if a version bump commit was made

      # - name: Commit version bump changes
      #   run: |
      #     git add bumpversion.cfg pyproject.toml
      #     git commit -m "Bump version"
      #     git push origin ${{ steps.vars.outputs.branch_name }} --follow-tags

      - name: Push all changes and tags
        run: |
          git push origin ${{ steps.vars.outputs.branch_name }} --follow-tags
#          git push --tags  # Push all tags to the remote
#          git push origin ${{ steps.vars.outputs.branch_name }}  # Push the branch

      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          title: "Bump version"
          body: "Automated version bump"
          base: fix_bumpversion
          branch: ${{ steps.vars.outputs.branch_name }}
          delete-branch: true  # optional: auto-delete branch after merge

      - name: Check outputs
        if: ${{ steps.cpr.outputs.pull-request-number }}
        run: |
          echo "Pull Request Number - ${{ steps.cpr.outputs.pull-request-number }}"
          echo "Pull Request URL - ${{ steps.cpr.outputs.pull-request-url }}"

      - name: Enable auto-merge for PR
        uses: peter-evans/enable-pull-request-automerge@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          pull-request-number: ${{ steps.cpr.outputs.pull-request-number }}
          merge-method: squash  
